//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOTNET_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int orderid { get; set; }
        public string productname { get; set; }
        public Nullable<int> amount { get; set; }
        public byte[] productimage { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual User User { get; set; }
    }
}
